server:
  port: 8099
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: sendius
      uri: mongodb+srv://Ramos:Sendius20.@sendius.hn5j58g.mongodb.net/
  mail:
    host: andresramosr20@gmail.com
    password: Sendius11.
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: andresydana611@gmail.com
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 983960659996-htu8vjsgb093fej6mb54hspmiq7u5c63.apps.googleusercontent.com
            client-secret: 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
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  thymeleaf:
    prefix: classpath:/templates/
